# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Repomap < Formula
  desc "Deterministic repository intelligence for AI coding agents."
  homepage "https://github.com/karanjasani/agentkit"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/karanjasani/agentkit/releases/download/v0.1.0/repomap_0.1.0_darwin_amd64.tar.gz"
      sha256 "548c9905286cf575c4a8339bca47e45b1e60137ff16cdec5c035b66c8007217f"

      define_method(:install) do
        bin.install "repomap"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/karanjasani/agentkit/releases/download/v0.1.0/repomap_0.1.0_darwin_arm64.tar.gz"
      sha256 "10edbd02a00979a4bde62f2fbd944b64093069abfdd543a55a3b98f2e1b0fb40"

      define_method(:install) do
        bin.install "repomap"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/karanjasani/agentkit/releases/download/v0.1.0/repomap_0.1.0_linux_amd64.tar.gz"
      sha256 "ea78a1bdfe9e5273439fed313e249eacf86adec18c81d8e1380afdc6e1e11850"
      define_method(:install) do
        bin.install "repomap"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/karanjasani/agentkit/releases/download/v0.1.0/repomap_0.1.0_linux_arm64.tar.gz"
      sha256 "27c7e3963bf64abc39effddd6ac11d71acb90b0de3c3703d85d6936294d0ce1c"
      define_method(:install) do
        bin.install "repomap"
      end
    end
  end

  test do
    system "#{bin}/repomap", "--version"
  end
end
