# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Repomap < Formula
  desc "Deterministic repository intelligence for AI coding agents."
  homepage "https://github.com/karanjasani/agentkit"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/karanjasani/agentkit/releases/download/v0.2.0/repomap_0.2.0_darwin_amd64.tar.gz"
      sha256 "f243668ef55a41a33dedfde96bf56865aa6e8ab97dac086aac7a5e05fbfe6f8d"

      define_method(:install) do
        bin.install "repomap"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/karanjasani/agentkit/releases/download/v0.2.0/repomap_0.2.0_darwin_arm64.tar.gz"
      sha256 "c2c5dec9c7b37bfa275ea940dc790708a1821c28d0977ef0997c95ae90a15f5e"

      define_method(:install) do
        bin.install "repomap"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/karanjasani/agentkit/releases/download/v0.2.0/repomap_0.2.0_linux_amd64.tar.gz"
      sha256 "9d8eb6c83e3a7c3d40db6cc0667a5ce5a3993210c190064e7dde3d6b11d88d26"
      define_method(:install) do
        bin.install "repomap"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/karanjasani/agentkit/releases/download/v0.2.0/repomap_0.2.0_linux_arm64.tar.gz"
      sha256 "2f77ac50067b2f2e53b9d5ac19de1eee415260ca022e8134f357aadb42376990"
      define_method(:install) do
        bin.install "repomap"
      end
    end
  end

  test do
    system "#{bin}/repomap", "--version"
  end
end
